/**
 * Languages configuration and offline fallback neural dictionary
 * Project: AI-Based Real-Time Multilingual Communication Assistant
 * CGC University Mohali - Department of AI & Data Science
 */

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', speechCode: 'en-US', ttsLang: 'en-US', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳', speechCode: 'hi-IN', ttsLang: 'hi-IN', dir: 'ltr' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳', speechCode: 'pa-IN', ttsLang: 'pa-IN', dir: 'ltr' },
  { code: 'es', name: 'Spanish', native: 'Español', flag: '🇪🇸', speechCode: 'es-ES', ttsLang: 'es-ES', dir: 'ltr' },
  { code: 'fr', name: 'French', native: 'Français', flag: '🇫🇷', speechCode: 'fr-FR', ttsLang: 'fr-FR', dir: 'ltr' },
  { code: 'de', name: 'German', native: 'Deutsch', flag: '🇩🇪', speechCode: 'de-DE', ttsLang: 'de-DE', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', native: '日本語', flag: '🇯🇵', speechCode: 'ja-JP', ttsLang: 'ja-JP', dir: 'ltr' },
  { code: 'zh', name: 'Chinese (Mandarin)', native: '中文', flag: '🇨🇳', speechCode: 'zh-CN', ttsLang: 'zh-CN', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', native: 'العربية', flag: '🇸🇦', speechCode: 'ar-SA', ttsLang: 'ar-SA', dir: 'rtl' },
  { code: 'ru', name: 'Russian', native: 'Русский', flag: '🇷🇺', speechCode: 'ru-RU', ttsLang: 'ru-RU', dir: 'ltr' },
  { code: 'it', name: 'Italian', native: 'Italiano', flag: '🇮🇹', speechCode: 'it-IT', ttsLang: 'it-IT', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', native: 'Português', flag: '🇵🇹', speechCode: 'pt-PT', ttsLang: 'pt-PT', dir: 'ltr' },
  { code: 'ko', name: 'Korean', native: '한국어', flag: '🇰🇷', speechCode: 'ko-KR', ttsLang: 'ko-KR', dir: 'ltr' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳', speechCode: 'bn-IN', ttsLang: 'bn-IN', dir: 'ltr' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', speechCode: 'ta-IN', ttsLang: 'ta-IN', dir: 'ltr' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳', speechCode: 'te-IN', ttsLang: 'te-IN', dir: 'ltr' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳', speechCode: 'mr-IN', ttsLang: 'mr-IN', dir: 'ltr' },
  { code: 'ur', name: 'Urdu', native: 'اردو', flag: '🇵🇰', speechCode: 'ur-PK', ttsLang: 'ur-PK', dir: 'rtl' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳', speechCode: 'gu-IN', ttsLang: 'gu-IN', dir: 'ltr' }
];

// Sample test prompts commonly used in College demo & travel
export const SAMPLE_PROMPTS = [
  { text: "Hello! How are you?", category: "Greetings" },
  { text: "Where is the bus stop?", category: "Travel" },
  { text: "Thank you very much!", category: "Polite" },
  { text: "Good morning, welcome to our AI project demonstration.", category: "Academic" },
  { text: "Can you help me please?", category: "General" },
  { text: "What is the weather like today?", category: "General" },
  { text: "I am a student at CGC University Mohali.", category: "Academic" }
];

// Comprehensive multilingual fallback dictionary
export const FALLBACK_DICTIONARY = {
  "hello": {
    hi: "नमस्ते",
    pa: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    es: "¡Hola!",
    fr: "Bonjour",
    de: "Hallo",
    ja: "こんにちは",
    zh: "你好",
    ar: "مرحبا",
    ru: "Здравствуйте",
    it: "Ciao",
    pt: "Olá",
    ko: "안녕하세요",
    bn: "হ্যালো",
    ta: "வணக்கம்",
    te: "నమస్కారం",
    mr: "नमस्कार",
    ur: "ہیلو",
    gu: "નમસ્તે"
  },
  "hello! how are you?": {
    hi: "नमस्ते! आप कैसे हैं?",
    pa: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?",
    es: "¡Hola! ¿Cómo estás?",
    fr: "Bonjour! Comment allez-vous?",
    de: "Hallo! Wie geht es dir?",
    ja: "こんにちは！お元気ですか？",
    zh: "你好！你好吗？",
    ar: "مرحبا! كيف حالك؟",
    ru: "Здравствуйте! Как ваши дела?",
    it: "Ciao! Come stai?",
    pt: "Olá! Como você está?",
    ko: "안녕하세요! 어떻게 지내세요?",
    bn: "হ্যালো! আপনি কেমন আছেন?",
    ta: "வணக்கம்! நீங்கள் எப்படி இருக்கிறீர்கள்?",
    te: "నమస్కారం! మీరు ఎలా ఉన్నారు?",
    mr: "नमस्कार! तुम्ही कसे आहात?",
    ur: "ہیلو! آپ کیسے ہیں؟",
    gu: "નમસ્તે! તમે કેમ છો?"
  },
  "where is the bus stop?": {
    hi: "बस स्टॉप कहाँ है?",
    pa: "ਬੱਸ ਸਟਾਪ ਕਿੱਥੇ ਹੈ?",
    es: "¿Dónde está la parada de autobús?",
    fr: "Où est l'arrêt de bus?",
    de: "Wo ist die Bushaltestelle?",
    ja: "バス停はどこですか？",
    zh: "公共汽车站在哪里？",
    ar: "أين هي محطة الحافلات؟",
    ru: "Где находится автобусная остановка?",
    it: "Dov'è la fermata dell'autobus?",
    pt: "Onde fica o ponto de ônibus?",
    ko: "버스 정류장이 어디인가요?",
    bn: "বাস স্টপ কোথায়?",
    ta: "பேருந்து நிறுத்தம் எங்கே?",
    te: "బస్ స్టాప్ ఎక్కడ ఉంది?",
    mr: "बस स्टॉप कुठे आहे?",
    ur: "بس اسٹاپ کہاں ہے؟",
    gu: "બસ સ્ટોપ ક્યાં છે?"
  },
  "thank you very much": {
    hi: "आपका बहुत-बहुत धन्यवाद",
    pa: "ਤੁਹਾਡਾ ਬਹੁਤ ਬਹੁਤ ਧੰਨਵਾਦ",
    es: "Muchas gracias",
    fr: "Merci beaucoup",
    de: "Vielen Dank",
    ja: "どうもありがとうございます",
    zh: "非常感谢",
    ar: "شكرا جزيلا لك",
    ru: "Большое спасибо",
    it: "Grazie mille",
    pt: "Muito obrigado",
    ko: "대단히 감사합니다",
    bn: "আপনাকে অনেক ধন্যবাদ",
    ta: "மிக்க நன்றி",
    te: "చాలా ధన్యవాదాలు",
    mr: "खूप खूप धन्यवाद",
    ur: "بہت بہت شکریہ",
    gu: "ખુબ ખુબ આભાર"
  },
  "thank you very much!": {
    hi: "आपका बहुत-बहुत धन्यवाद!",
    pa: "ਤੁਹਾਡਾ ਬਹੁਤ ਬਹੁਤ ਧੰਨਵਾਦ!",
    es: "¡Muchas gracias!",
    fr: "Merci beaucoup!",
    de: "Vielen Dank!",
    ja: "どうもありがとうございます！",
    zh: "非常感谢！",
    ar: "شكرا جزيلا لك!",
    ru: "Большое спасибо!",
    it: "Grazie mille!",
    pt: "Muito obrigado!",
    ko: "대단히 감사합니다!",
    bn: "আপনাকে অনেক ধন্যবাদ!",
    ta: "மிக்க நன்றி!",
    te: "చాలా ధన్యవాదాలు!",
    mr: "खूप खूप धन्यवाद!",
    ur: "بہت بہت شکریہ!",
    gu: "ખુબ ખુબ આભાર!"
  },
  "good morning": {
    hi: "सुप्रभात",
    pa: "ਸ਼ੁਭ ਸਵੇਰ",
    es: "Buenos días",
    fr: "Bonjour",
    de: "Guten Morgen",
    ja: "おはようございます",
    zh: "早上好",
    ar: "صباح الخير",
    ru: "Доброе утро",
    it: "Buongiorno",
    pt: "Bom dia",
    ko: "좋은 아침입니다",
    bn: "সুপ্রভাত",
    ta: "காலை வணக்கம்",
    te: "శుభోదయం",
    mr: "शुभ प्रभात",
    ur: "صبح بخیر",
    gu: "સુપ્રભાત"
  },
  "good morning, welcome to our ai project demonstration.": {
    hi: "सुप्रभात, हमारे एआई प्रोजेक्ट प्रदर्शन में आपका स्वागत है।",
    pa: "ਸ਼ੁਭ ਸਵੇਰ, ਸਾਡੇ ਏਆਈ ਪ੍ਰੋਜੈਕਟ ਪ੍ਰਦਰਸ਼ਨ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ।",
    es: "Buenos días, bienvenidos a la demostración de nuestro proyecto de IA.",
    fr: "Bonjour, bienvenue à la démonstration de notre projet d'IA.",
    de: "Guten Morgen, willkommen zu unserer KI-Projektdemonstration.",
    ja: "おはようございます、AIプロジェクトのデモンストレーションへようこそ。",
    zh: "早上好，欢迎来到我们的人工智能项目演示。",
    ar: "صباح الخير، مرحبًا بكم في عرض مشروع الذكاء الاصطناعي الخاص بنا.",
    ru: "Доброе утро, добро пожаловать на презентацию нашего проекта ИИ.",
    it: "Buongiorno, benvenuti alla dimostrazione del nostro progetto di IA.",
    pt: "Bom dia, bem-vindo à demonstração do nosso projeto de IA.",
    ko: "좋은 아침입니다, AI 프로젝트 시연에 오신 것을 환영합니다.",
    bn: "সুপ্রভাত, আমাদের এআই প্রকল্প প্রদর্শনে স্বাগতম।",
    ta: "காலை வணக்கம், எங்கள் AI திட்ட செயல்விளக்கத்திற்கு வரவேற்கிறோம்.",
    te: "శుభోదయం, మా AI ప్రాజెక్ట్ ప్రదర్శనకు స్వాగతం.",
    mr: "शुभ प्रभात, आमच्या AI प्रकल्प प्रात्यक्षिकात आपले स्वागत आहे.",
    ur: "صبح بخیر، ہمارے اے آئی پروجیکٹ کے مظاہرے میں خوش آمدید۔",
    gu: "સુપ્રભાત, અમારા AI પ્રોજેક્ટ પ્રદર્શનમાં આપનું સ્વાગત છે."
  },
  "what is the weather like today?": {
    hi: "आज मौसम कैसा है?",
    pa: "ਅੱਜ ਮੌਸਮ ਕਿਹੋ ਜਿਹਾ ਹੈ?",
    es: "¿Cómo está el clima hoy?",
    fr: "Quel temps fait-il aujourd'hui?",
    de: "Wie ist das Wetter heute?",
    ja: "今日の天気はどうですか？",
    zh: "今天天气怎么样？",
    ar: "كيف هو الطقس اليوم؟",
    ru: "Какая сегодня погода?",
    it: "Com'è il tempo oggi?",
    pt: "Como está o tempo hoje?",
    ko: "오늘 날씨가 어때요?",
    bn: "আজ আবহাওয়া কেমন?",
    ta: "இன்று வானிலை எப்படி இருக்கிறது?",
    te: "ఈ రోజు వాతావరణం ఎలా ఉంది?",
    mr: "आज हवामान कसे आहे?",
    ur: "آج موسم کیسا ہے؟",
    gu: "આજે હવામાન કેવું છે?"
  },
  "i am a student at cgc university mohali.": {
    hi: "मैं सीजीसी यूनिवर्सिटी मोहाली का छात्र हूँ।",
    pa: "ਮੈਂ ਸੀਜੀਸੀ ਯੂਨੀਵਰਸਿਟੀ ਮੋਹਾਲੀ ਦਾ ਵਿਦਿਆਰਥੀ ਹਾਂ।",
    es: "Soy estudiante en la Universidad CGC de Mohali.",
    fr: "Je suis étudiant à l'Université CGC de Mohali.",
    de: "Ich bin Student an der CGC Universität Mohali.",
    ja: "私はCGC大学モハリの学生です。",
    zh: "我是莫哈利CGC大学的学生。",
    ar: "أنا طالب في جامعة CGC موهالي.",
    ru: "Я студент университета CGC в Мохали.",
    it: "Sono uno studente dell'Università CGC di Mohali.",
    pt: "Sou estudante da Universidade CGC Mohali.",
    ko: "저는 CGC 모할리 대학교 학생입니다.",
    bn: "আমি সিজিসি ইউনিভার্সিটি মোহালির একজন ছাত্র।",
    ta: "நான் சிஜிசி பல்கலைக்கழக மொஹாலியின் மாணவர்.",
    te: "నేను CGC యూనివర్సిటీ మొహాలి విద్యార్థిని.",
    mr: "मी सीजीसी युनिव्हर्सिटी मोहालीचा विद्यार्थी आहे.",
    ur: "میں سی جی سی یونیورسٹی موہالی کا طالب علم ہوں۔",
    gu: "હું સીજીસી યુનિવર્સિટી મોહાલીનો વિદ્યાર્થી છું."
  },
  "can you help me please?": {
    hi: "क्या आप कृपया मेरी मदद कर सकते हैं?",
    pa: "ਕੀ ਤੁਸੀਂ ਕਿਰਪਾ ਕਰਕੇ ਮੇਰੀ ਮਦਦ ਕਰ ਸਕਦੇ ਹੋ?",
    es: "¿Puedes ayudarme, por favor?",
    fr: "Pouvez-vous m'aider s'il vous plaît?",
    de: "Können Sie mir bitte helfen?",
    ja: "助けていただけますか？",
    zh: "你能帮帮我吗？",
    ar: "هل يمكنك مساعدتي من فضلك؟",
    ru: "Не могли бы вы мне помочь, пожалуйста?",
    it: "Puoi aiutarmi per favore?",
    pt: "Você pode me ajudar, por favor?",
    ko: "저를 좀 도와주시겠어요?",
    bn: "আপনি কি দয়া করে আমাকে সাহায্য করতে পারেন?",
    ta: "தயவுசெய்து எனக்கு உதவ முடியுமா?",
    te: "దయచేసి మీరు నాకు సహాయం చేయగలరా?",
    mr: "कृपया तुम्ही मला मदत करू शकता का?",
    ur: "کیا آپ برائے مہربانی میری مدد کر سکتے ہیں؟",
    gu: "શું તમે કૃપા કરીને મને મદદ કરી શકો છો?"
  }
};
